# Generated by Django 3.1.4 on 2021-02-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('nick_name', models.CharField(max_length=250, verbose_name='nick name')),
                ('email', models.CharField(max_length=250, verbose_name='email')),
                ('password', models.CharField(max_length=250, verbose_name='password')),
                ('repeat_password', models.CharField(max_length=250, verbose_name='repeat password')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
